// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDps6wTDg-p5j4ePDqQZDa_LD0nZwGuLRk',
    appId: '1:532850332803:web:b45248241d0f8c7fed37b6',
    messagingSenderId: '532850332803',
    projectId: 'forge-by-alpfit',
    authDomain: 'forge-by-alpfit.firebaseapp.com',
    storageBucket: 'forge-by-alpfit.firebasestorage.app',
    measurementId: 'G-8KFF8QLQ68',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuNfHtNMAwP39w-IOPTAzEj3VFy1d5c2Y',
    appId: '1:532850332803:android:8d38b7e7cf4956d2ed37b6',
    messagingSenderId: '532850332803',
    projectId: 'forge-by-alpfit',
    storageBucket: 'forge-by-alpfit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXVncxCKD9g2UtI2OEBD3HY6zm-SmZj0U',
    appId: '1:532850332803:ios:24a1529a55f66e4ded37b6',
    messagingSenderId: '532850332803',
    projectId: 'forge-by-alpfit',
    storageBucket: 'forge-by-alpfit.firebasestorage.app',
    iosBundleId: 'com.example.forgeSeniorProjectVersion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXVncxCKD9g2UtI2OEBD3HY6zm-SmZj0U',
    appId: '1:532850332803:ios:24a1529a55f66e4ded37b6',
    messagingSenderId: '532850332803',
    projectId: 'forge-by-alpfit',
    storageBucket: 'forge-by-alpfit.firebasestorage.app',
    iosBundleId: 'com.example.forgeSeniorProjectVersion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDps6wTDg-p5j4ePDqQZDa_LD0nZwGuLRk',
    appId: '1:532850332803:web:dd826ceea76d267ced37b6',
    messagingSenderId: '532850332803',
    projectId: 'forge-by-alpfit',
    authDomain: 'forge-by-alpfit.firebaseapp.com',
    storageBucket: 'forge-by-alpfit.firebasestorage.app',
    measurementId: 'G-0SDVFZD979',
  );
}
